### ISSUE TITLE
Setup new business management tooling

### ISSUE THREAD

**Issue by control-alt-kaboom** [Control-Alt-Kaboom-Project/hugo-framework#21]
With the aquisition of the new business properties there is some setup and configuration that needs to be added to them so that they can be exposed, developed and tracked.  The following is a generalized list of the tasks that need to completed.

### Task List
- [ ] Setup google administration for the new domains
- [ ] Setup gmail for the new domains
- [ ] Setup godaddy for the domains
- [ ] Setup github for each of the domains.
- [ ] have the domains deployed to a parking page
